xxx:
  joint_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 11.0,i: 0.06, d: 0.0005}
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 11.0,i: 0.06, d: 0.0005}
  