#---standard pioneer footprint---
#---(in meters)---
footprint: [[0.403, -0.288], [0.403, 0.288], [-0.403, 0.288], [-0.403, -0.288]]

transform_tolerance: 0.2
map_type: voxel

always_send_full_costmap: true

obstacle_layer:
  enable: true
  publish_voxel_map: false
  resolution: 0.1
  transform_tolerance: 0.5
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  z_resolution: 0.4
  z_voxels: 1
  observation_sources: scan rs_d435i_lower_scan rs_d435i_upper_scan cloud_upper cloud_lower
  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    obstacle_range: 5.0
    raytrace_range: 5.01

  rs_d435i_lower_scan:
    data_type: LaserScan
    topic: /rs_d435i_2/scan
    inf_is_valid: true 
    marking: true
    clearing: true
    # obstacle_range: 3.0
    # raytrace_range: 3.1
    min_obstacle_height: 0.15 # here we can use the floor visibility...
    max_obstacle_height: 1.6

  rs_d435i_upper_scan:
    data_type: LaserScan
    topic: /rs_d435i_1/scan
    inf_is_valid: true 
    marking: true
    clearing: true
    obstacle_range: 1.0
    raytrace_range: 1.1
    min_obstacle_height: 0.15
    max_obstacle_height: 1.6

  cloud_upper: 
    data_type: PointCloud2
    topic: rs_d435i_1/depth/color/points
    marking: true
    clearing: true
    min_obstacle_height: 0.15
    max_obstacle_height: 1.6
    obstacle_range: 0.5
    raytrace_range: 0.6

  cloud_lower: 
    data_type: PointCloud2
    topic: rs_d435i_2/depth/color/points
    marking: true
    clearing: true
    min_obstacle_height: 0.15 # here we can use the floor visibility...
    max_obstacle_height: 1.6
    # obstacle_range: 3.0
    # raytrace_range: 3.1

global_inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

local_inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.25  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  # map_topic:            "/map"
  map_topic:            "/map_nav"